# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Memorials' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FacebookLikeReaction'
  pod 'FSCalendar'
  pod 'TimelineTableViewCell'
  pod 'SimpleCheckbox'
  # Pods for memorials

end
